-- Дамп структуры для таблица world.city
DROP TABLE IF EXISTS city;
CREATE TABLE IF NOT EXISTS city
(
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  Name        char(35) NOT NULL DEFAULT '',
  CountryCode char(3)  NOT NULL DEFAULT '',
  District    char(20) NOT NULL DEFAULT '',
  Population  int      NOT NULL DEFAULT '0'
);

-- create type continents as enum ('Asia', 'Europe', 'North America', 'Africa', 'Oceania', 'Antarctica', 'South America');

DROP TABLE IF EXISTS country;
CREATE TABLE IF NOT EXISTS country
(
  id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  Code           char(3)        NOT NULL DEFAULT '',
  Name           char(52)       NOT NULL DEFAULT '',
  Continent      char(52)       NOT NULL DEFAULT 'Asia',
  Region         char(26)       NOT NULL DEFAULT '',
  SurfaceArea    NUMERIC(10, 2) NOT NULL DEFAULT '0.00',
  IndepYear      int                     DEFAULT NULL,
  Population     int            NOT NULL DEFAULT '0',
  LifeExpectancy NUMERIC(3, 1)           DEFAULT NULL,
  GNP            NUMERIC(10, 2)          DEFAULT NULL,
  GNPOld         NUMERIC(10, 2)          DEFAULT NULL,
  LocalName      char(45)       NOT NULL DEFAULT '',
  GovernmentForm char(45)       NOT NULL DEFAULT '',
  HeadOfState    char(60)                DEFAULT NULL,
  Capital        int                     DEFAULT NULL,
  Code2          char(2)        NOT NULL DEFAULT ''
);